### ISSUE TITLE
Report bug when install Release Page's addon zip file

### ISSUE THREAD

**Issue by MatchaChoco010** [BlenderNPR/BEER#145]
Hello. I would like to report a bug.

## My environment
My environment is as follows
- Windows 11 Pro
- AMD Ryzen 9 5900X
- NVIDIA GeForce RTX 3080 Ti
- 64GB RAM
- Blender: 2.93.5 LTS
- Malt: Release-latest 4003c51

## Bug Description
I downloaded Malt from Release, installed it and tried to test it out, but it froze for a few seconds every time I performed an operation.

https://user-images.githubusercontent.com/20170107/136643967-5dc21c03-b06f-4b82-9095-44d5a0b676f3.mp4

When I looked at the console, I got the following error.

![スクリーンショット 2021-10-09 125146](https://user-images.githubusercontent.com/20170107/136643986-3111b422-e339-4dde-b1c6-045492362026.png)

> Unable to load numpy_formathandler accelerator from OpenGL_accelerate

This is a good reference for this error. https://github.com/mcfletch/pyopengl/issues/46

When you build PyOpenGL without numpy, the numpy_formathandler module is not built.

On GitHub Actions CI, the build is running in an environment without numpy, so the numpy_formathandler module is not built, and the add-on being released does not contain numpy_formathandler.
On the other hand, since numpy is included in the Python of Blender where the add-on is executed, it tries to load numpy_formathandler.
This resulted in an error.

So I installed numpy in the GitHub Actions build environment as well and tried to build and run it.
Then I got the following error.

![image](https://user-images.githubusercontent.com/20170107/136644004-5567915d-3ca0-4a97-a703-d70eb4872450.png)

> AttributeError: ("type object 'OpenGL_accelerate.numpy_formathandler.NumpyHandler' has no attribute '__reduce_cython__'", 4, <OpenGL. platform.baseplatform.glGetInternalformativ object at 0x000001E43B076580>)

You can refer to this Issue for more information about this error. https://github.com/tlecomte/friture/issues/177

Blender's numpy was version 1.19.5.
On the other hand, the numpy used to build GitHub Actions is 1.21.2.

Because the version of numpy in Blender and the version of numpy installed in GitHub Actions are different, the OpenGL_accelerate.numpy_formathandler module is causing an error.

## Possible solutions
There are two possible solutions to this problem.

### Solution 1
Upgrade the version of numpy in Blender.
I upgraded numpy in Blender's python environment, and Malt worked.

However, I think this method has a problem.
The version of the installed python package is tied to the version of Blender.
If you upgrade the version of numpy in Blender, other add-ons may have errors.

### Solution 2
Make the Python environment used to build GitHub Actions into Blender's Python environment.

If you build PyOpenGL and PyOpenGL_accelerate in the same environment as Blender's Python, you should not get errors due to numpy version inconsistencies between the execution and build environments.
If you build according to https://github.com/bnpr/Malt/blob/Development/docs/Setup-BlenderMalt-for-Development.md in your hand instead of GitHub Actions, you can use Blender's Python and running setup_blender_addon.py.
In the same way, if you build the addon using Blender's Python, you should not have any problems.

If you take this approach, you will need to prepare a GitHub Actions environment for each build version of Blender in the worst case, since the numpy version can change for each build version of Blender.

I think it would be a good idea to build with 2.93.5 LTS numpy and 3 alpha numpy and distribute them respectively.
It is confusing that each version of Blender has a different zip file of add-ons to install, but it is unavoidable if you take this solution.

---
These are the only two solutions I could think of.
Are there any other good solutions?

I am willing to go so far as to create a PR that fixes this problem.
Since the problem is occurring in my environment, it would be more reasonable for me to create a fix PR that I can verify will fix the problem.
Once I decide how to deal with the problem, I would like to create a modified PR on my end.

So, I would like to discuss with you how we should deal with this problem.

Thank you very much for your time.

**Comment by pragma37** [comment]
Hello! Thank you for the detailed report.

I'm not sure your initial problem is actually related to NumPy.
The "Unable to load numpy_formathandler accelerator from OpenGL_accelerate" shouldn't prevent Malt from working correctly. It shows for all users (me too).
Malt doesn't load NumPy arrays into OpenGL and even if it did, I think it would just fall back into the normal "not accelerated" PyOpenGL implementation.

So there must be another problem.
Does the [Development version](https://github.com/bnpr/Malt/releases/tag/Development-latest) work for you?
It's very ahead of the Release branch and it's probably more stable at this point (it will be merged soon).
If the Development version doesn't work for you, could you post your [log files](https://github.com/bnpr/Malt#bug-reports)?


That said, it's probably a good idea to build BlenderMalt with Blender's Python, and a PR would be very welcome.
There's no need to distribute multiple addons versions, BlenderMalt already ships with [dependencies built for different Python versions](https://github.com/bnpr/Malt/blob/6ed92fb152f0e221fbbdd449e705f86522441733/.github/workflows/BlenderMalt.yml#L68) and [decides what version it should use at runtime](https://github.com/bnpr/Malt/blob/Development/BlenderMalt/__init__.py#L20).

**Comment by MatchaChoco010** [comment]
Thanks for the replies!
I'll try the Development version and report the results when I do!

**Comment by MatchaChoco010** [comment]
Hello!

My environment is:
- Windows 11 pro
- blender-2.93.5-windows-x64 portable
- AMD Ryzen 9 5900X
- NVIDIA GeForce RTX 3080 Ti
- 64GB RAM

I tried to set up a development environment following [this link](https://github.com/bnpr/Malt/blob/Development/docs/Setup-BlenderMalt-for-Development.md), but it failed to build and install `PyOpenGL_accelerate`.

<details>
<summary>Error log</summary>

```
PS F:\github.com\bnpr\Malt> C:\Users\orito\Dropbox\PC\Documents\Blender` Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe F:\github.com\bnpr\Malt\scripts\setup_blender_addon.py --scripts-folder C:\Users\orito\Dropbox\PC\Documents\BlenderUserScripts
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/.build
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.0+0538acc04
Copyright (C) Microsoft Corporation.All rights reserved.

  Checking Build System
  Building Custom Rule F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/CMakeLists.txt
  CBlenderMalt.cpp
     ライブラリ F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/.build/Release/CBlenderMalt.lib とオブジェクト F:/github.com/bnpr/
  Malt/BlenderMalt/CBlenderMalt/.build/Release/CBlenderMalt.exp を作成中
  CBlenderMalt.vcxproj -> F:\github.com\bnpr\Malt\BlenderMalt\CBlenderMalt\.build\Release\CBlenderMalt.dll
  Building Custom Rule F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/CMakeLists.txt
-- Install configuration: "Release"
-- Installing: F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/CBlenderMalt.lib
-- Installing: F:/github.com/bnpr/Malt/BlenderMalt/CBlenderMalt/CBlenderMalt.dll
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using std::filesystem
CMake Deprecation Warning at .build/_deps/rapidjson-src/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: F:/github.com/bnpr/Malt/Malt/GL/GLSLParser/.build
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.0+0538acc04
Copyright (C) Microsoft Corporation.All rights reserved.

  Checking Build System
  Building Custom Rule F:/github.com/bnpr/Malt/Malt/GL/GLSLParser/CMakeLists.txt
  main.cpp
  GLSLParser.vcxproj -> F:\github.com\bnpr\Malt\Malt\GL\GLSLParser\.bin\GLSLParser.exe
  Building Custom Rule F:/github.com/bnpr/Malt/Malt/GL/GLSLParser/CMakeLists.txt
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/github.com/bnpr/Malt/Bridge/ipc/.build
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.0+0538acc04
Copyright (C) Microsoft Corporation.All rights reserved.

  Checking Build System
  Building Custom Rule F:/github.com/bnpr/Malt/Bridge/ipc/CMakeLists.txt
  ipc.c
F:\github.com\bnpr\Malt\Bridge\ipc\ipc.h(255,94): warning C4267: '関数': 'size_t' から 'DWORD' に変換しました。データが
失われているかもしれません。 [
F:\github.com\bnpr\Malt\Bridge\ipc\.build\Ipc.vcxproj]
     ライブラリ F:/github.com/bnpr/Malt/Bridge/ipc/.build/Release/Ipc.lib とオブジェクト F:/github.com/bnpr/Malt/Bridge/ipc/.build/
  Release/Ipc.exp を作成中
  Ipc.vcxproj -> F:\github.com\bnpr\Malt\Bridge\ipc\.build\Release\Ipc.dll
  Building Custom Rule F:/github.com/bnpr/Malt/Bridge/ipc/CMakeLists.txt
-- Install configuration: "Release"
-- Installing: F:/github.com/bnpr/Malt/Bridge/ipc/Ipc.lib
-- Installing: F:/github.com/bnpr/Malt/Bridge/ipc/Ipc.dll
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/github.com/bnpr/Malt/Bridge/renderdoc/.build
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.0+0538acc04
Copyright (C) Microsoft Corporation.All rights reserved.

  Checking Build System
  Building Custom Rule F:/github.com/bnpr/Malt/Bridge/renderdoc/CMakeLists.txt
  renderdoc_wrapper.c
     ライブラリ F:/github.com/bnpr/Malt/Bridge/renderdoc/.build/Release/renderdoc_wrapper.lib とオブジェクト F:/github.com/bnpr/Mal
  t/Bridge/renderdoc/.build/Release/renderdoc_wrapper.exp を作成中
  renderdoc_wrapper.vcxproj -> F:\github.com\bnpr\Malt\Bridge\renderdoc\.build\Release\renderdoc_wrapper.dll
  Building Custom Rule F:/github.com/bnpr/Malt/Bridge/renderdoc/CMakeLists.txt
-- Install configuration: "Release"
-- Installing: F:/github.com/bnpr/Malt/Bridge/renderdoc/renderdoc_wrapper.lib
-- Installing: F:/github.com/bnpr/Malt/Bridge/renderdoc/renderdoc_wrapper.dll
Collecting glfw
  Using cached glfw-2.3.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl (491 kB)
Installing collected packages: glfw
Successfully installed glfw-2.3.0
WARNING: You are using pip version 20.2.3; however, version 21.3 is available.
You should consider upgrading via the 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe -m pip install --upgrade pip' command.
Collecting PyOpenGL
  Using cached PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
Installing collected packages: PyOpenGL
Successfully installed PyOpenGL-3.1.5
WARNING: You are using pip version 20.2.3; however, version 21.3 is available.
You should consider upgrading via the 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe -m pip install --upgrade pip' command.
Collecting PyOpenGL_accelerate
  Using cached PyOpenGL-accelerate-3.1.5.tar.gz (538 kB)
Using legacy 'setup.py install' for PyOpenGL-accelerate, since package 'wheel' is not installed.
Installing collected packages: PyOpenGL-accelerate
    Running setup.py install for PyOpenGL-accelerate ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\orito\\AppData\\Local\\Temp\\pip-install-5zsu0wrs\\pyopengl-accelerate\\setup.py'"'"'; __file__='"'"'C:\\Users\\orito\\AppData\\Local\\Temp\\pip-install-5zsu0wrs\\pyopengl-accelerate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\orito\AppData\Local\Temp\pip-record-f10zwx7r\install-record.txt' --single-version-externally-managed --home 'C:\Users\orito\AppData\Local\Temp\pip-target-gypubro1' --compile --install-headers 'C:\Users\orito\AppData\Local\Temp\pip-target-gypubro1\include\python\PyOpenGL-accelerate'
         cwd: C:\Users\orito\AppData\Local\Temp\pip-install-5zsu0wrs\pyopengl-accelerate\
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\OpenGL_accelerate
    copying OpenGL_accelerate\__init__.py -> build\lib.win-amd64-3.9\OpenGL_accelerate
    running build_ext
    skipping 'src\wrapper.c' Cython extension (up-to-date)
    skipping 'src\formathandler.c' Cython extension (up-to-date)
    skipping 'src\arraydatatype.c' Cython extension (up-to-date)
    skipping 'src\errorchecker.c' Cython extension (up-to-date)
    skipping 'src\vbo.c' Cython extension (up-to-date)
    skipping 'src\nones_formathandler.c' Cython extension (up-to-date)
    skipping 'src\latebind.c' Cython extension (up-to-date)
    skipping 'src\buffers_formathandler.c' Cython extension (up-to-date)
    skipping 'src\numpy_formathandler.c' Cython extension (up-to-date)
    building 'OpenGL_accelerate.wrapper' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\orito\AppData\Local\Temp\pip-install-5zsu0wrs\pyopengl-accelerate\.. -IC:\Users\orito\AppData\Local\Temp\pip-install-5zsu0wrs\pyopengl-accelerate\src -IC:\Users\orito\AppData\Local\Temp\pip-install-5zsu0wrs\pyopengl-accelerate -IC:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\include -IC:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc\wrapper.c /Fobuild\temp.win-amd64-3.9\Release\src\wrapper.obj
    wrapper.c
    src\wrapper.c(4): fatal error C1083: include ファイルを開けません。'Python.h':No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\orito\\AppData\\Local\\Temp\\pip-install-5zsu0wrs\\pyopengl-accelerate\\setup.py'"'"'; __file__='"'"'C:\\Users\\orito\\AppData\\Local\\Temp\\pip-install-5zsu0wrs\\pyopengl-accelerate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\orito\AppData\Local\Temp\pip-record-f10zwx7r\install-record.txt' --single-version-externally-managed --home 'C:\Users\orito\AppData\Local\Temp\pip-target-gypubro1' --compile --install-headers 'C:\Users\orito\AppData\Local\Temp\pip-target-gypubro1\include\python\PyOpenGL-accelerate' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 21.3 is available.
You should consider upgrading via the 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe -m pip install --upgrade pip' command.
ERROR: pip install PyOpenGL_accelerate failed.
Traceback (most recent call last):
  File "F:\github.com\bnpr\Malt\scripts\install_dependencies.py", line 12, in <module>
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', dependency, '--target', malt_dependencies_path])
  File "C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\orito\\Dropbox\\PC\\Documents\\Blender Launcher\\stable\\blender-2.93.5-windows-x64\\2.93\\python\\bin\\python.exe', '-m', 'pip', 'install', 'PyOpenGL_accelerate', '--target', 'F:\\github.com\\bnpr\\Malt\\scripts\\..\\Malt\\.Dependencies-39']' returned non-zero exit status 1.
Collecting Pyrr
  Using cached pyrr-0.10.3-py3-none-any.whl (46 kB)
Collecting multipledispatch
  Using cached multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Collecting numpy
  Using cached numpy-1.21.2-cp39-cp39-win_amd64.whl (14.0 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, multipledispatch, numpy, Pyrr
Successfully installed Pyrr-0.10.3 multipledispatch-0.6.0 numpy-1.21.2 six-1.16.0
WARNING: You are using pip version 20.2.3; however, version 21.3 is available.
You should consider upgrading via the 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe -m pip install --upgrade pip' command.
Collecting psutil
  Using cached psutil-5.8.0-cp39-cp39-win_amd64.whl (246 kB)
Installing collected packages: psutil
Successfully installed psutil-5.8.0
WARNING: You are using pip version 20.2.3; however, version 21.3 is available.
You should consider upgrading via the 'C:\Users\orito\Dropbox\PC\Documents\Blender Launcher\stable\blender-2.93.5-windows-x64\2.93\python\bin\python.exe -m pip install --upgrade pip' command.
```
</details>

It seems that the error was not caused by numpy, but by `PyOpenGL_accelerate` not being built.

A `PyOpenGL_accelerate` package of Windows 11 has no wheel version, and then `pip install` try to install from source and `Python.h` was not found.
I think this is because Blender's Python does not have an include and libs directory.
I installed Python 3.9.2, which is the same version as Blender's Python, and copied the includes and libs directories to Blender's python directory, and was able to build Malt.
![image](https://user-images.githubusercontent.com/20170107/137574702-b1dd4ae8-84e3-4696-9d29-b5eaabce819d.png)

This got it working correctly now!
![スクリーンショット 2021-10-16 140000](https://user-images.githubusercontent.com/20170107/137574633-4113428f-a555-442b-b721-c1aac73c1836.png)

I think the installation script may need to be added a script to place the includes and libs directories into Blender's Python directory while installing Malt.

**Comment by pragma37** [comment]
Before trying to compile it yourself, did you download the Development version and it did not work?

If it didn't, could you try the pre-built version and manually delete the OpenGL_accelerate folder?
```BlenderMalt/.MaltPath/Malt/.Dependencies-39/OpenGL_accelerate```

**Comment by MatchaChoco010** [comment]
Hello! I'm really sorry for the late reply.
I've downloaded the latest Development version of Malt and tried it out.
It's working great, no problems whatsoever!

I'll post the log just in case, but it's working without any problems.
[malt 2021-10-30(09-37).log](https://github.com/bnpr/Malt/files/7445497/malt.2021-10-30.09-37.log)

Thank you for your reply and generous support!

**Comment by pragma37** [comment]
Great!
Thank you for reporting.

The Release version was recently synced with the Development branch, so it should work as well.
