### ISSUE TITLE
OpenGL module missing on windows

### ISSUE THREAD

**Issue by Numeross** [BlenderNPR/BEER#2]
On windows, with blender LTS, I had to uninstall and reinstall PyOpenGL :
```
 cd '.\Program Files\Blender Foundation\Blender 2.83\2.83\python\bin\'
.\python.exe -m pip uninstall PyOpenGL
.\python.exe -m pip install PyOpenGL
```

The error was : 
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderMalt\__init__.py", line 26, in <module>
    from . import MaltMaterial
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderMalt\MaltMaterial.py", line 7, in <module>
    from .Malt.Shader import Shader
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderMalt\Malt\__init__.py", line 3, in <module>
    from . import GL
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderMalt\Malt\GL.py", line 5, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'
```

**Comment by BlenderNPR** [comment]
The first time you activate the add-on, it will auto install that.

**Comment by vladfaust** [comment]
I know it's mentioned in the README, but running Blender as administrator for the first time installing the addon solved the issue. 🙂
