### ISSUE TITLE
add-on Install fail with Apple silicon

### ISSUE THREAD

**Issue by daiyadove** [BlenderNPR/BEER#217]
### Malt version

latest at 2022-01-04

### Blender version

2.93(for Apple Silicon version)

### OS

macOS Big Sur

### Hardware info

Apple M1 | 16GB

### Issue description and reproduction steps

I tried to install the add-on on a   M1 chip(Apple silicon) machine and got the following error

```
OSError: dlopen(/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib, 6): no suitable image found.  Did find:
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture
```
(BTW, I changed the version to 3 and got the same result)

`wrong architecture` 
Does this mean that the M1 chip machines are not yet supported?
Is there any way to avoid this?
Also, when will the response be available?

### Attachments

```
bpy.data.window_managers["WinMan"].addon_search = "malt"
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/__init__.py", line 187, in register
    for module in get_modules():
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/__init__.py", line 175, in get_modules
    from . import MaltTextures, MaltMeshes, MaltLights, MaltProperties, MaltPipeline, MaltNodes, MaltMaterial, MaltRenderEngine
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 10, in <module>
    from . import MaltPipeline, MaltMeshes, MaltMaterial, CBlenderMalt
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/__init__.py", line 13, in <module>
    CBlenderMalt = ctypes.CDLL(os.path.join(src_dir, library))
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib, 6): no suitable image found.  Did find:
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/__init__.py", line 187, in register
    for module in get_modules():
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/__init__.py", line 175, in get_modules
    from . import MaltTextures, MaltMeshes, MaltLights, MaltProperties, MaltPipeline, MaltNodes, MaltMaterial, MaltRenderEngine
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 10, in <module>
    from . import MaltPipeline, MaltMeshes, MaltMaterial, CBlenderMalt
  File "/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/__init__.py", line 13, in <module>
    CBlenderMalt = ctypes.CDLL(os.path.join(src_dir, library))
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib, 6): no suitable image found.  Did find:
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture
	/Users/xxx/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/CBlenderMalt/libCBlenderMalt.dylib: mach-o, but wrong architecture

```

**Comment by pragma37** [comment]
Hi!
> Does this mean that the M1 chip machines are not yet supported?

Yes, the prebuilt binaries are for x86_64 only.

> Is there any way to avoid this?

You could try to compile the addon libraries in your own machine:
https://github.com/bnpr/Malt/blob/Development/docs/Setup-BlenderMalt-for-Development.md

But even then, most Malt features won't work due to the limited OpenGL support in MacOS.
https://github.com/bnpr/Malt#requirements

**Comment by benjamindahl** [comment]
Will there be a better support for MacOS in the future?

**Comment by pragma37** [comment]
@benjamindahl
I wish, but I don't have Apple hardware to test on, and even if I had, OpenGL support in MacOS is terrible.

I actually plan to remove the pre-built Mac binaries from the release builds on the next Malt update, since at the moment the addon in Mac is not that useful unless you're a programmer.

I'll keep the Mac related code in case someone wants to provide Mac support or I have the resources to provide it myself at some point, but unless I get propper funding that seems unlikely in the short and medium term.

**Comment by pragma37** [comment]
Deleting this, since we no longer provide Mac support.
