### ISSUE TITLE
NPR_Pipeline/Nodes/Common missing

### ISSUE THREAD

**Issue by Joeboy** [BlenderNPR/BEER#233]
### Malt version

1.0 Preview

### Blender version

Blender 3.0.1

### OS

Ubuntu Linux 21.10

### Hardware info

Intel i7-9750H | 16GB RAM | Nvidia Quadro T2000

### Issue description and reproduction steps

Hi! After installing the add-on and switching to the malt Engine, I'm seeing an error where it seems to be trying to access `.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipelines/NPR_Pipeline/Nodes/Common`, but it's not present. After creating the folder I can switch to the malt engine without error.

### Attachments

```
blender
Read prefs: /home/joe/.config/blender/3.0/config/userpref.blend
Traceback (most recent call last):
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/PipelineGraph.py", line 191, in setup_reflection
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 562, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
FILEPATH :  /home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipelines/NPR_Pipeline/Nodes/Common
Traceback (most recent call last):
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/PipelineGraph.py", line 191, in setup_reflection
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 562, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
FILEPATH :  /home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipelines/NPR_Pipeline/Nodes/Common
```

**Comment by pragma37** [comment]
This one was harmless, but better to remove unnecessary warnings.
Thank you for the report!
