### ISSUE TITLE
Can't activate addon

### ISSUE THREAD

**Issue by vidur501** [BlenderNPR/BEER#263]
### Malt version

Release 44fe8e5/Dev pre-release 103f4dd

### Blender version

Blender 3.0.1/3.2.0alpha

### OS

Manjaro [Stable Update] 2022-02-27

### Hardware info

Radeon HD 7770

### Issue description and reproduction steps

Hello,

it is not possible to activate your addon. Please help.

**1) Release 44fe8e5 ( - no version info displayed - )
   a) Blender 3.0.1:**
Installation works:
`Modules Installed (BlenderMalt) from '/home/vidur/Downloads/BlenderMalt-Linux Release 44fe8e5.zip' into '/home/vidur/.config/blender/3.0/scripts/addons'`
but when trying to activate it, this error appears:
```
Traceback (most recent call last):
  File "/home/vidur/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/__init__.py", line 191, in register
    Bridge.reload()
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Bridge/__init__.py", line 5, in reload
    from . import Client_API, Server, Material, Mesh, Texture
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 7, in <module>
    import glfw
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies-39/glfw/__init__.py", line 43, in <module>
    raise ImportError("Failed to load GLFW3 shared library.")
ImportError: Failed to load GLFW3 shared library.

```
   **b) Blender 3.2.0 alpha** branch: master, commit date: 2022-02-28 18:18, hash: `rB96492903aa28`
Installation works:
`Modules Installed (BlenderMalt) from '/home/vidur/Downloads/BlenderMalt-Linux Release 44fe8e5.zip' into '/home/vidur/.config/blender/3.2/scripts/addons'`

but when trying to activate it, this error appears:
```
Traceback (most recent call last):
  File "/home/vidur/blender-git/build_linux/bin/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/__init__.py", line 187, in register
    for module in get_modules():
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/__init__.py", line 175, in get_modules
    from . import MaltTextures, MaltMeshes, MaltLights, MaltProperties, MaltPipeline, MaltNodes, MaltMaterial, MaltRenderEngine
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/MaltTextures.py", line 4, in <module>
    from . import MaltPipeline
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/MaltPipeline.py", line 6, in <module>
    from . import MaltMaterial, MaltMeshes, MaltTextures
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/MaltMaterial.py", line 6, in <module>
    from . MaltProperties import MaltPropertyGroup
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/MaltProperties.py", line 5, in <module>
    from Malt.Parameter import Type, Parameter, MaterialParameter
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/__init__.py", line 5, in <module>
    from Malt import Pipeline
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipeline.py", line 7, in <module>
    from Malt.GL.GL import *
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/GL.py", line 5, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'
```

**2) Dev pre-release 103f4dd ("1.0.0 beta")
a) Blender 3.0.1:**
Installation works:
Modules Installed (BlenderMalt) from '/home/vidur/Downloads/BlenderMalt-Linux Dev pre-release 103f4dd.zip' into '/home/vidur/.config/blender/3.0/scripts/addons'
but when trying to activate it, this error appears:
```
Traceback (most recent call last):
  File "/home/vidur/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/__init__.py", line 125, in register
    for module in get_modules():
  File "/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/__init__.py", line 116, in get_modules
    from . MaltNodes import _init_ as MaltNodes
ImportError: cannot import name '_init_' from 'BlenderMalt.MaltNodes' (/home/vidur/.config/blender/3.0/scripts/addons/BlenderMalt/MaltNodes.py)
```

**b) Blender 3.2.0 alpha** branch: master, commit date: 2022-02-28 18:18, hash: `rB96492903aa28`
Installation works:
`Modules Installed (BlenderMalt) from '/home/vidur/Downloads/BlenderMalt-Linux Dev pre-release 103f4dd.zip' into '/home/vidur/.config/blender/3.2/scripts/addons'`
but when trying to activate it, this error appears:
```
Traceback (most recent call last):
  File "/home/vidur/blender-git/build_linux/bin/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/__init__.py", line 125, in register
    for module in get_modules():
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/__init__.py", line 115, in get_modules
    from . import MaltUtils, MaltTextures, MaltMeshes, MaltLights, MaltProperties, MaltPipeline, MaltMaterial, MaltRenderEngine
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 5, in <module>
    from Malt.GL import GL
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/GL.py", line 3, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'
```

### Attachments

none

**Comment by pragma37** [comment]
Malt is not expected to work yet in Blender 3.2.
The Python dependencies that Malt ships with are not compatible with the Python version that Blender 3.1+ uses.

For the other errors:

The error in the Release version (1a) might be caused by a GLFW incompatibility between Ubuntu and Manjaro. You can try to manually delete the .Dependencies-39 folder from BlenderMalt (BlenderMalt\.MaltPath\Malt\.Dependencies-39).

Then install manually these dependencies. Locate the Python binary that Blender uses and run:
```<blender-python-path> -m pip glfw PyOpenGL==3.1.5 PyOpenGL_accelerate==3.1.5 Pyrr psutil```

The error in the Development version (2a) is caused because you installed the new version without removing the older first, so some older files are still there.

---

Since Blender is going to start updating Python versions more often, I plan to simply download the appropriate dependencies at startup (if needed). So this info will be outdated soon.

**Comment by vidur501** [comment]
Thanks!
