### ISSUE TITLE
Trying to enable the addon on a fresh 2.9 install gives this error

### ISSUE THREAD

**Issue by sourozowy** [BlenderNPR/BEER#3]
on a new 2.9 install i got:

```
Traceback (most recent call last):
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py", line 26, in <module>
    from . import MaltMaterial
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltMaterial.py", line 10, in <module>
    from . import MaltPipeline
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 17, in <module>
    __PIPELINE__ = PipelineTest()
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\Malt\PipelineTest.py", line 89, in __init__
    super().__init__()
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\Malt\Pipeline.py", line 71, in __init__
    self.quad = Mesh(positions, indices)
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\Malt\Mesh.py", line 23, in __init__
    glGenBuffers(1, self.EBO)
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\wrapper.py", line 678, in wrapperCall
    raise err
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Users\Joseph\Desktop\blender-2.90.0-699cefefd009-windows64\2.90\python\lib\site-packages\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glGenBuffers,
	pyArgs = (
		1,
		<BlenderMalt.Malt.GL.c_long_Array_1 object at 0x0000017FF2FAAA48>,
	),
	cArgs = (
		1,
		<BlenderMalt.Malt.GL.c_long_Array_1 object at 0x0000017FF2FAAA48>,
	),
	cArguments = (
		1,
		<BlenderMalt.Malt.GL.c_long_Array_1 object at 0x0000017FF2FAAA48>,
	)
)
```

I made sure to enable admin

**Comment by pragma37** [comment]
Looks like there was no OpenGL context enabled when the pipeline was initialized. Does it always happen?
If you try to render the viewport, does it work?
If it doesn't, could you post your system info ? (Inside Blender, Help > Save System Info)

**Comment by pragma37** [comment]
It might have been fixed now. Try to download the latest version.

**Comment by sourozowy** [comment]
the latest version has fixed my installation issue. Bless xo
