### ISSUE TITLE
High RAM usage & Laggy UI

### ISSUE THREAD

**Issue by ABugNamedBeetle** [BlenderNPR/BEER#34]
With just default cube in Viewport Shading
![image](https://user-images.githubusercontent.com/62416701/103343292-c33aa780-4ab1-11eb-81bd-620b06295e66.png)
Error in INFO:
Python: Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltRenderEngine.py", line 273, in view_draw
    GL.glGetIntegerv(GL.GL_FRAMEBUFFER_BINDING, fbo)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glGetIntegerv,
	pyArgs = (
		GL_FRAMEBUFFER_BINDING,
		<Malt.GL.GL.c_long_Array_1 object at 0x00000270CFA5E548>,
	),
	cArgs = (
		GL_FRAMEBUFFER_BINDING,
		<Malt.GL.GL.c_long_Array_1 object at 0x00000270CFA5E548>,
	),
	cArguments = (
		GL_FRAMEBUFFER_BINDING,
		<Malt.GL.GL.c_long_Array_1 object at 0x00000270CFA5E548>,
	)
)

location: <unknown location>:-1

Specs : Intel I5 1035G1 and Intel UHD G1

**Comment by pragma37** [comment]
Malt uses very high quality rendering settings by default.
Go to Properties Panel > Scene > Malt Settings and lower the Transparency Layers (1 should be enough for the viewport) and the ShadowMaps resolution (1024 or 512 should be fine).

Does that help?

**Comment by ABugNamedBeetle** [comment]
yes it did help, but F12 rendering doesn't works, as before I'm getting error for every glGenBuffers calls
Python: Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltRenderEngine.py", line 206, in render
    scene = self.get_scene(None, depsgraph, True)
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltRenderEngine.py", line 179, in get_scene
    add_object(obj, obj.matrix_world)
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltRenderEngine.py", line 110, in add_object
    malt_mesh = MaltMeshes.load_mesh(obj)
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltMeshes.py", line 84, in load_mesh
    positions = load_VBO(positions)
  File "D:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons_contrib\BlenderMalt\MaltMeshes.py", line 78, in load_VBO
    glGenBuffers(1, VBO)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glGenBuffers,
	pyArgs = (
		1,
		<Malt.GL.GL.c_long_Array_1 object at 0x000001C67B2907C8>,
	),
	cArgs = (
		1,
		<Malt.GL.GL.c_long_Array_1 object at 0x000001C67B2907C8>,
	),
	cArguments = (
		1,
		<Malt.GL.GL.c_long_Array_1 object at 0x000001C67B2907C8>,
	)
)

location: <unknown location>:-1

**Comment by pragma37** [comment]
Glad it helped!

Yes, F12 rendering doesn't work on Intel cards, it's a known issue (#23).

**Comment by ABugNamedBeetle** [comment]
why you are using your own OpenGL wrapper and why not bgl one.

**Comment by pragma37** [comment]
BGL is very incomplete. There are lots of missing functions, no way to check for extensions, it doesn't work with ctypes...
It doesn't even support unsigned int buffers.

PyOpenGL is not my own wrapper, it's the most widely used OpenGL wrapper for Python.
It's 100% complete, including extensions, and checks for OpenGL errors, so debugging is much easier.

**Comment by ABugNamedBeetle** [comment]
then there will be two rendering context one by blender and other by openGL

**Comment by Lateasusual** [comment]
> then there will be two rendering context one by blender and other by openGL

See https://developer.blender.org/D8305 - Blender passes an OpenGL context to BEER

**Comment by pragma37** [comment]
> then there will be two rendering context one by blender and other by openGL

That's not how it works. OpenGL contexts and OpenGL function loaders are orthogonal.
PyOpenGL just looks for function adresses on the OS OpenGL library.

**Comment by ABugNamedBeetle** [comment]
do you have the barebone for like [https://docs.blender.org/api/current/bpy.types.RenderEngine.html#simple-render-engine](url)
with openGL, i looked into view_draw() but I'm getting lost.
