### ISSUE TITLE
Nothing rendered in Blender 3.2

### ISSUE THREAD

**Issue by zNightlord** [BlenderNPR/BEER#346]
### Malt version

Development

### Blender version

Blender 3.2.0

### OS

Windows 10 64bit

### Hardware info

 Intel(R) HD Graphics 4600 Intel 4.3.0 | Quadro K2100M/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 426.50

### Issue description and reproduction steps

Malt worked in Blender 3.1 but not for 3.2 

Install Malt Lastest Development (02.07.2022)
Default scene or the example file
Switch to Malt rendered mode, nothing rendered the console starts spaming traceback.
 
 There was another issue but it apparently not happen anymore.
 
<details> 
 <summary>
Traceback
 </summary>

```
Traceback (most recent call last):
2022-07-07 00:24:13,240 [ERROR] root: Traceback (most recent call last):

  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 362, in view_draw
2022-07-07 00:24:13,242 [ERROR] root:   File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 362, in view_draw

    2022-07-07 00:24:13,242 [ERROR] root:
render_texture = Texture(resolution, texture_format, data_format, pixels.buffer(), mag_filter=mag_filter)2022-07-07 00:24:13,242 [ERROR] root: render_texture = Texture(resolution, texture_format, data_format, pixels.buffer(), mag_filter=mag_filter)

2022-07-07 00:24:13,243 [ERROR] root:

  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\.MaltPath\Malt\GL\Texture.py", line 22, in __init__
2022-07-07 00:24:13,243 [ERROR] root:   File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\.MaltPath\Malt\GL\Texture.py", line 22, in __init__

    2022-07-07 00:24:13,244 [ERROR] root:
glTexImage2D(GL_TEXTURE_2D, 0, self.internal_format, resolution[0], resolution[1], 2022-07-07 00:24:13,244 [ERROR] root: glTexImage2D(GL_TEXTURE_2D, 0, self.internal_format, resolution[0], resolution[1],

2022-07-07 00:24:13,244 [ERROR] root:

  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
2022-07-07 00:24:13,245 [ERROR] root:   File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__

  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
2022-07-07 00:24:13,245 [ERROR] root:   File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__

  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
2022-07-07 00:24:13,246 [ERROR] root:   File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call

  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
2022-07-07 00:24:13,247 [ERROR] root:   File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call

  File "src/wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
2022-07-07 00:24:13,247 [ERROR] root:   File "src/wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call

  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\.MaltPath\Malt\.Dependencies-310\OpenGL\GL\images.py", line 456, in __call__
2022-07-07 00:24:13,248 [ERROR] root:   File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderMalt\.MaltPath\Malt\.Dependencies-310\OpenGL\GL\images.py", line 456, in __call__

    2022-07-07 00:24:13,252 [ERROR] root:
arrayType = arrays.GL_CONSTANT_TO_ARRAY_TYPE[ images.TYPE_TO_ARRAYTYPE[ type ] ]2022-07-07 00:24:13,252 [ERROR] root: arrayType = arrays.GL_CONSTANT_TO_ARRAY_TYPE[ images.TYPE_TO_ARRAYTYPE[ type ] ]

2022-07-07 00:24:13,252 [ERROR] root:

KeyError2022-07-07 00:24:13,252 [ERROR] root: KeyError
: 2022-07-07 00:24:13,253 [ERROR] root: :
(35863, <OpenGL.GL.images.ImageInputConverter object at 0x00000213B1822A40>)2022-07-07 00:24:13,253 [ERROR] root: (35863, <OpenGL.GL.images.ImageInputConverter object at 0x00000213B1822A40>)

2022-07-07 00:24:13,253 [ERROR] root:
```

</details> 

![image](https://user-images.githubusercontent.com/61040487/177611774-8784ff10-89e8-4c6f-8fb9-a6fb369cce4c.png)

### Attachments

[malt 2022-07-07(00-24).log](https://github.com/bnpr/Malt/files/9057033/malt.2022-07-07.00-24.log)

**Comment by pragma37** [comment]
Could you try to set the Bit Depth (Viewport) to 16 or 32?

BTW, you should disable the *Debug Mode* in the addon settings.

**Comment by zNightlord** [comment]
Yeah it's fixed when you change to that.

**Comment by pragma37** [comment]
It's good to know that's the issue. Thanks!

Malt tries to find the best texture format for certain operations and that can depend on the GPU model.
The OpenGL library we use doesn't have support for some of the rarer formats, but it should be possible to find a workaround.

I'm going to keep this open so I don't forget about it.
