### ISSUE TITLE
(WinError 5) Access is denied

### ISSUE THREAD

**Issue by SadiqMH** [BlenderNPR/BEER#394]
### Malt version

Release

### Blender version

Blender 3.3.0

### OS

Windows10 64bit

### Hardware info

Intel i7-12650H   | Nvidia RTX 3070 Mobile

### Issue description and reproduction steps

Can't install the addon

1- Open blender 3.3.0
2- Go to Edit/Preferences
3- Go to Addons.
4- Press Install.
5- Choose the latest release of the addon zip file.
6- Error showing.

### Attachments
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 656, in execute
    _module_filesystem_remove(path_addons, f)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 48, in _module_filesystem_remove
    shutil.rmtree(f_full)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\*User*\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\BlenderMalt\\.MaltPath\\Malt\\.Dependencies-310\\xxhash\\_xxhash.cp310-win_amd64.pyd'

**Comment by pragma37** [comment]
You need to uninstall the previously installed version before installing a new one.
https://github.com/bnpr/Malt#uninstall
