### ISSUE TITLE
Malt crashes Blender in reasonably large project with Geforce GTX 1080-Ti

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#515]
### Malt version

Node Groups

### Blender version

Blender 3.6.1

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | NVIDIA GeForce GTX 1080 Ti 

### Issue description and reproduction steps

Crash happens on loading blend file, unless if the BlenderMalt add on is disabled, I mean sometimes it still wants to crash on load, I seem to have to try a couple of times, but eventually it'll open.

Once opening, and reactivating the addon, Malt spams the system console with this error. (Have not changed rendering engine to Malt yet)

```
File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\MaltMaterial.py", line 227, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()
AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'
```

Blender locks up once switching the renderer, and attempting to enter render preview. It spams the log with references to the .malt.autogenerated folder, however, I'm experiencing this in pretty much all of my blend files, and the solution seems to be to delete the autogenerated folder and let it generate a new one. 

### Attachments

Crash on load:
[malt 2023-07-29(10-31).log](https://github.com/bnpr/Malt/files/12207484/malt.2023-07-29.10-31.log)
[act2-mephel-x-balloons-2_2.crash.txt](https://github.com/bnpr/Malt/files/12207485/act2-mephel-x-balloons-2_2.crash.txt)

**Comment by dibli-goost** [comment]
Here's a traceback I'm getting in the system console with the crash on load 

```
Exception ignored in: <function UBO.__del__ at 0x000001D0ECF0BD00>
Traceback (most recent call last):
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\.MaltPath\Malt\GL\Shader.py", line 154, in __del__
    glDeleteBuffers(1, self.buffer[0])
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\.MaltPath\Malt\.Dependencies-310\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glDeleteBuffers, check for bool(glDeleteBuffers) before calling
Exception ignored in: <function Mesh.__del__ at 0x000001D0E68C5360>
Traceback (most recent call last):
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\.MaltPath\Malt\GL\Mesh.py", line 100, in __del__
    delete_buffer(self.EBO)
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\.MaltPath\Malt\GL\Mesh.py", line 98, in delete_buffer
    glDeleteBuffers(1, buffer)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderMalt\.MaltPath\Malt\.Dependencies-310\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glDeleteBuffers, check for bool(glDeleteBuffers) before calling
```

**Comment by pragma37** [comment]
>  Malt spams the system console with this error. (Have not changed rendering engine to Malt yet)

Do you have more than one scene and Malt is the selected rendererer there, maybe?

The crash happens in Blender, inside `b_bone_deform` .
Malt doesn't touch armatures in any way, but I see a warning in your log caused by an addon called `bone_selection_sets`.
I'd say that (or another armature related addon) is a lot more likely to be the cause, especially if it also happens sometimes with Malt disabled.

**Comment by dibli-goost** [comment]
Ah it does seem to be caused by a Rigify feature set, I didn't think to try and deactivate those individually before. There were multiple scenes as well. Don't understand the bone_selection_sets thing, I've been getting it for a long time, it's not even enabled so I don't know why it's throwing anything at all. Goes away if I enable it.

Seems to not be related to Malt after all. Closing issue.
