### ISSUE TITLE
Can't enable newly installed addon in Blender 4.0.2

### ISSUE THREAD

**Issue by Shararamosh** [BlenderNPR/BEER#571]
### Malt version

Release

### Blender version

Blender 4.0.2

### OS

Windows 11 Pro 64 bits

### Hardware info

Intel Core i5 9600K, 32 GB of RAM, NVIDIA GeForce RTX 4060 Ti

### Issue description and reproduction steps

Enabling the addon in Blender 4.0.2 causes it to throw error about module named "xxhash" not being found.

### Attachments

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\shara\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderMalt\__init__.py", line 198, in register
    for module in get_modules():
  File "C:\Users\shara\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderMalt\__init__.py", line 185, in get_modules
    from . import MaltUtils, MaltTextures, MaltMeshes, MaltLights, MaltProperties, MaltPipeline, MaltMaterial, MaltRenderEngine
  File "C:\Users\shara\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 2, in <module>
    import xxhash
ModuleNotFoundError: No module named 'xxhash'

**Comment by noctiswhole** [comment]
Did you install the version for blender 4.0?

https://github.com/bnpr/Malt/releases/tag/blender-4.0-last-version

**Comment by Shararamosh** [comment]
I've installed the latest version - thought it was compatible with Blender 4.0. Now that I've installed version for 4.0 it does not throw any errors. Thanks!
